import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getPictureCategory } from "../lib/cos";

export async function getServerSideProps(context) {
  return await getPictureCategory();
}

export default function Home(props) {
  console.log(props);
  const { buketList } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>暖暖的世界</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>暖暖的世界</h1>

        <p className={styles.description}>welcome~</p>

        <div className={styles.grid}>
          {buketList.map((item) => (
            <a
              key={item.Prefix}
              href={`nn/${item.Prefix}`}
              className={styles.card}
            >
              <h2>{item.Prefix}</h2>
              <p>描述</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
